/*
 * WARNING: This file is automatically generated by the Ant build script.
 * DO NOT EDIT THIS FILE MANUALLY.
 */
package org.word.editor.core.util; // <-- IMPORTANT: Change this to your package

/**
 * Provides the application version string generated at build time.
 */
public final class AppVersion {

    /**
     * The build version string (e.g., "yyyy.MM.dd.HHmm" or "DEV-BUILD").
     */
    private static final String VERSION = "2025.11.15.1955"; // <-- Ant replaces this token

    /**
     * Gets the application's build version.
     * @return The version string.
     */
    public static String getVersion() {
        return VERSION;
    }

    // Private constructor to prevent instantiation
    private AppVersion() {}
}